// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgwiglyaujwymgfahnmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnd2lnbHlhdWp3eW1nZmFobm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjM4NjcsImV4cCI6MjA2ODA5OTg2N30.DCbKBkI2IYiBw5-aLEHl_k_tG8VcqXeA-r1oxe44ZyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});